package com.asg.payroll.employeeSettlement.dto;

import com.asg.common.lib.dto.LovGetListDto;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EmployeeSettlementDto {

    private Long transactionPoid;
    private LocalDate transactionDate;
    private Long groupPoid;
    private Long companyPoid;
    private String docRef;
    private Long employeePoid;
    private String settlementType;
    private String leaveType;
    private Long leaveRequestPoid;
    private String leaveApprovalFormAttached;
    private String homeCountryPhone;
    private LocalDate leaveStartDate;
    private LocalDate leaveEndDate;
    private LocalDate rejoinDate;
    private Long leaveDays;
    private Long eligibleLeaveDays;
    private Long balanceLeaveDays;
    private BigDecimal leaveSalary;
    private String ticketEligiblity;
    private String ticketIssueType;
    private Long ticketIssuedCount;
    private Long ticketEncashment;
    private Long airSectorPoid;
    private Long attendancePoid;
    private BigDecimal basicSalary;
    private BigDecimal basicSalaryPayable;
    private Long workedDays;
    private Long absentDays;
    private BigDecimal absentAmount;
    private Long ot1Hrs;
    private Long ot1Amt;
    private Long ot2Hrs;
    private Long ot2Amt;
    private Long shortHrs;
    private Long shortHrsAmount;
    private Long medicalDays;
    private Long fixedAllowance;
    private Long hraAllowance;
    private Long travelAllowance;
    private Long communicationAllowance;
    private Long transportAllowance;
    private Long specialAllowance;
    private Long otherAllowance;
    private Long otherAllowGl;
    private Long arrears;
    private Long gosiDeduction;
    private Long loanDeduction;
    private Long phoneDeduction;
    private Long medicalInsurance;
    private Long recurringDeduction;
    private Long otherDeductions;
    private Long otherDedGl;
    private Long totAllowance;
    private Long totDeductions;
    private BigDecimal grossSalary;
    private BigDecimal netSalary;
    private LocalDate dateOfLeaving;
    private String assetHandoverFormAttach;
    private String reasonForLeaving;
    private Long totalYearsService;
    private Long totalIndemnityDays;
    private Long indemnityInThreeYr;
    private Long indemnityAfterThreeYr;
    private Long totalIndemnityAmount;
    private LocalDate prevIndemnityDate;
    private BigDecimal totalSettlementAmt;
    private String paymentMethod;
    private String settlementStatus;
    private String remarks;
    private String deleted;
    private LocalDate lastWorkingDate;
    private String withoutSalary;
    private LocalDate gosiFromDate;
    private LocalDate gosiToDate;
    private BigDecimal basicSalaryPayable2;
    private Long workedDays2;
    private Long fixedAllowance2;
    private Long hraAllowance2;
    private Long transportAllowance2;
    private Long specialAllowance2;
    private Long gosiDeduction2;
    private Long loanDeduction2;
    private Long medicalInsurance2;
    private Long totAllowance2;
    private Long totDeductions2;
    private Long grossSalary2;
    private BigDecimal netSalary2;
    private Long travelAllowance2;
    private BigDecimal communicationAllowance2;
    private String otherAllowanceDetails;
    private String otherDeductionsDetails;
    private LocalDate payroll1Date;
    private LocalDate payroll2Date;
    private LocalDate joinDate;
    private String jvDocRef;
    private Long jvPoid;
    private String lastLeaveDetails;
    private Long workDaysFromLastLeave;
    private Long paidLeavesTaken;
    private Long attendance2Poid;
    private Long fixedOt;
    private Long fixedOt2;
    private Long basicFixAlw;
    private Long basicFixOt;
    private LocalDate lastRejoinDate;
    private Long basicEligibleLeaveDays;
    private BigDecimal basicSalPerDay;
    private BigDecimal grossSalPerDay;
    private Long basicHra;
    private Long basicTransport;
    private Long exgratia;
    private Long exgratiaGl;
    private Long roundOff;
    private String paymentDocType;
    private String paymentDocRef;
    private Long paymentDocPoid;
    private LocalDate paymentValueDate;
    private String paymentPayeeName;
    private Long paymentBankPoid;
    private String paymentPrePrinted;
    private Long crPoid;
    private String indemnityFirstThreeYrDays;
    private String indemnityAfterThreeYrDays;
    private Long indemnityServiceDays;
    private Long otherAllowance2;
    private Long otherAllowGl2;
    private String otherAllowanceDetails2;
    private Long leaveAbsentDays;
    private Long leaveWorkDaysStage1;
    private Long leaveEligibleLeaveStage1;
    private String lastTicketDetails;
    private Long lateDeductionAmt;
    private Long ticketsEarned;
    private BigDecimal excessVisaCharges;
    private LocalDate ticketTillDate;
    private BigDecimal indemnityPaidAmt;
    private Long indemnityWithoutPayDays;
    private String recovVisaCost;
    private String recovGosiCost;
    private String recovLmraCost;
    private String recovMdinsCost;
    private String recovTicketCost;
    private Long ticketEligiblityTemp;
    private Long indemnityEligibleDays;
    private Long sioShareIndemnity;
    private String indmntyMnthsCompany;
    private String indmntyMnthsSio;
    private Long indemnityProvAmount;

    private List<LoanDeductionDto> loanDeductionDetails;

}
